#!/bin/sh

### BEGIN INIT INFO
# Provides:        monitoring-speedtest
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start the speedtest monitoring
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/usr/bin/monitoring-daemon
MODULE=speedtest
PIDFILE=/var/run/monitoring-${MODULE}.pid

test -x $DAEMON || exit 5

# if [ -r /etc/default/ntp ]; then
#         . /etc/default/ntp
# fi

# if [ -e /var/lib/ntp/ntp.conf.dhcp ]; then
#         NTPD_OPTS="$NTPD_OPTS -c /var/lib/ntp/ntp.conf.dhcp"
# fi

case $1 in
        start)
                log_daemon_msg "Starting monitoring-${MODULE}" "monitoring-${MODULE}"
                start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE ${MODULE}
                status=$?
                log_end_msg $status
                ;;
        stop)
                log_daemon_msg "Stopping monitoring-${MODULE}" "monitoring-${MODULE}"
                start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
                log_end_msg $?
                rm -f $PIDFILE
                ;;
        restart)
                $0 stop && sleep 2 && $0 start
                ;;
        try-restart)
                if $0 status >/dev/null; then
                        $0 restart
                else
                        exit 0
                fi
                ;;
        status)
                status_of_proc $DAEMON "monitoring-${MODULE}"
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|try-restart|status}"
                exit 2
                ;;
esac
