name: Build the daemon packages
on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-docker:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: rclsilver-org/monitoring-daemon
      DOCKER_FILE: daemon/Dockerfile

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Login to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Debug version
        run:
            bash -x ./daemon/generate-version.sh

      - name: Generate the version
        id: version
        run:
            echo "value=$(./daemon/generate-version.sh)" >> "$GITHUB_OUTPUT"

      - name: Build the binaries
        run: |
            make -C daemon monitoring-daemon

      - name: Prepare the packages
        run: |
            for arch in amd64 mips64; do
                mkdir -p .debpkg-${arch}/usr/bin
                cp -R daemon/DEBIAN .debpkg-${arch}
                cp daemon/dist/monitoring-daemon-linux-${arch} .debpkg-${arch}/usr/bin/monitoring-daemon
            done

      - name: Build the package
        id: build_deb_amd64
        uses: jiro4989/build-deb-action@v3
        with:
          package: monitoring-daemon
          package_root: .debpkg-amd64
          maintainer: Thomas Bétrancourt <thomas@betrancourt.net>
          version: ${{ steps.version.outputs.value }}
          arch: 'amd64'
          desc: 'monitoring daemon'
          homepage: 'https://github.com/rclsilver-org/monitoring'

      - name: Build the package
        id: build_deb_mips64
        uses: jiro4989/build-deb-action@v3
        with:
          package: monitoring-daemon
          package_root: .debpkg-mips64
          maintainer: Thomas Bétrancourt <thomas@betrancourt.net>
          version: ${{ steps.version.outputs.value }}
          arch: 'mips'
          desc: 'monitoring daemon'
          homepage: 'https://github.com/rclsilver-org/monitoring'

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ${{ env.DOCKER_FILE }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.value }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Publish the release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ !startsWith(github.ref, 'refs/tags/v') && 'latest' || '' }}
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/v') }}
          title: ${{ startsWith(github.ref, 'refs/tags/v') && steps.version.outputs.value || 'Development Build' }}
          files: |
            daemon/dist/monitoring-daemon-linux-amd64
            daemon/dist/monitoring-daemon-linux-mips64
            ${{ steps.build_deb_amd64.outputs.file_name }}
            ${{ steps.build_deb_mips64.outputs.file_name }}
